name: MERN CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mongo-init:
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Waiting for MongoDB to start
        run: |
          while ! nc -z localhost 27017; do sleep 1; done

      - name: Seed tasks data to MongoDB
        working-directory: ./backend
        run: |
          npm install
          node seedTasksData.js

      - name: Run Backend unit tests
        working-directory: ./backend
        run: |
          npm install
          npm run test
